export const ADD_TODO = 'ADD_TODO'

export const DELETE_TODO = 'DELETE_TODO'

export const ADD_STAKER_TO_LIST = "ADD_STAKER_TO_LIST"

export const UPDATE_CURRENT_STAKER = "UPDATE_CURRENT_STAKER"

export const UPDATE_BANK_CONTRACT = "UPDATE_BANK_CONTRACT"

export const UPDATE_TEKENTOKENCONTRACT = "UPDATE_TEKETOKEN_CONTRACT"

export const CLEAN_STAKERS_LIST = "CLEAN_STAKERS_LIST"
